name: Daily Run

on:
  schedule:
    # Run at 1:05 AM UTC every day
    - cron: '5 1 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for git diff to work properly
        token: ${{ secrets.RSS_BOT_GITHUB_TOKEN }}  # Use the token for authentication
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Setup environment
      run: make ci-setup
        
    - name: Install dependencies
      run: make ci-install
        
    - name: Run script and commit changes
      run: |-
        make ci-run && make ci-commit 